chain_id = 11155111
nightfall = "0xbEF3D0bd93A45baA6bbaBD85d45293dE2258c0d1"
round_robin = "0x2b193206364fA4e6c3dA129428C230087c6f3F27"
x509 = "0x146305F231835B990666fF9f853773ecb72777B6"
verifier = "0xCf797927dC2Be747dF258e09c4AC72C613a510B2"
