nightfall_hash = "c83716b0cc4761aa570591b35052736eaa312c3bf20df7cb3e70e4b76cac3d82"
round_robin_hash = "bc02ef176cc3d34388b53500619070b64856e9df8ed4539c2ee425100bfa7240"
x509_hash = "6aff264507cc9ad8d22febd520d4c134f5dee3aa875e50b36f13200488f0a9e0"
